# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'body.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import QApplication,QMainWindow
from PyQt5.QtGui  import QImage,QPixmap
import sys
import cv2
import numpy as np
import time

r=np.random.RandomState()
def out(data):     #模拟返回
    a=list(r.randint(0,43,(7)))
    b = list(r.randint(0,43,(7)))
    str1="返回的数据"
    return a,b,str1

class Ui_MainWindow(object):

    def start_cap(self):
        self.cap = cv2.VideoCapture(0)
        self.label.setScaledContents(True)
        self.t = True
        while self.t:
            success, self.frame = self.cap.read()
            if success:
                show = cv2.cvtColor(self.frame, cv2.COLOR_BGR2RGB)
            showImage = QImage(show.data, show.shape[1], show.shape[0], QImage.Format_RGB888)

            self.label.setPixmap(QPixmap.fromImage(showImage))
            cv2.waitKey(1)     #调延时

    def go(self):
        self.cap = cv2.VideoCapture(0)
        self.label.setScaledContents(True)
        self.t = False
        self.F = True
        while self.F:
            success, self.frame = self.cap.read()
            if success:
                show = cv2.cvtColor(self.frame, cv2.COLOR_BGR2RGB)
            show = cv2.rectangle(show, (55, 67), (55 + 200, 67 + 200), (0, 255, 0), 2)
            showImage = QImage(show.data, show.shape[1], show.shape[0], QImage.Format_RGB888)

            self.label.setPixmap(QPixmap.fromImage(showImage))
            cv2.waitKey(1)  # 调延时
            time.sleep(0.5)  # 调延时
            in_data=self.frame
            num, strs, anu = out(in_data)

            self.pushButton_4.setText(str(num[0]))
            self.pushButton_6.setText(str(num[1]))
            self.pushButton_8.setText(str(num[2]))
            self.pushButton_10.setText(str(num[3]))
            self.pushButton_12.setText(str(num[4]))
            self.pushButton_14.setText(str(num[5]))
            self.pushButton_16.setText(str(num[6]))

            self.pushButton_5.setText(str(strs[0]))
            self.pushButton_7.setText(str(strs[1]))
            self.pushButton_9.setText(str(strs[2]))
            self.pushButton_11.setText(str(strs[3]))
            self.pushButton_13.setText(str(strs[4]))
            self.pushButton_15.setText(str(strs[5]))
            self.pushButton_17.setText(str(strs[6]))

            self.textBrowser.setText(anu)
            self.textBrowser_8.setText(anu)
            self.textBrowser_3.setText(anu)
            self.textBrowser_4.setText(anu)
            self.textBrowser_5.setText(anu)
            self.textBrowser_6.setText(anu)
            self.textBrowser_7.setText(anu)


    def end_cap(self):
        self.F = False
        self.t = False
        self.cap.release()
        cv2.destroyAllWindows()
        self.label.setText("s")

    def pause(self):
        self.F = False
        self.t = False
    def contiue(self):
        self.F = True
        self.t = True
        self.go()
        
    def setupUi(self, MainWindow):
        self.t=True
        self.F = True
        self.cap = cv2.VideoCapture(0)
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(915, 610)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 281, 81))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 80, 281, 81))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 160, 281, 81))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(180, 240, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_4")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(240, 240, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(240, 280, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(180, 280, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(240, 320, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(180, 320, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(240, 360, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(180, 360, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(240, 400, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(180, 400, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(240, 440, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(180, 440, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(240, 480, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(180, 480, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setGeometry(QtCore.QRect(240, 520, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setGeometry(QtCore.QRect(180, 520, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setObjectName("pushButton_19")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(283, 1, 611, 561))
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(1, 399, 181, 41))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_8 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_8.setGeometry(QtCore.QRect(1, 241, 181, 41))
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_5.setGeometry(QtCore.QRect(1, 281, 181, 41))
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(1, 517, 181, 41))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_7.setGeometry(QtCore.QRect(1, 438, 181, 41))
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_6.setGeometry(QtCore.QRect(1, 478, 181, 41))
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(1, 320, 181, 41))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(1, 360, 181, 41))
        self.textBrowser_3.setObjectName("textBrowser_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 915, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.start_cap)
        self.pushButton_3.clicked.connect(self.end_cap)
        self.pushButton_2.clicked.connect(self.go)
        self.pushButton_18.clicked.connect(self.pause)
        self.pushButton_19.clicked.connect(self.contiue)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "打开相机"))
        self.pushButton_2.setText(_translate("MainWindow", "开始行为识别"))
        self.pushButton_3.setText(_translate("MainWindow", "关闭相机"))
        self.pushButton_4.setText(_translate("MainWindow", "/"))
        self.pushButton_5.setText(_translate("MainWindow", "/"))
        self.pushButton_6.setText(_translate("MainWindow", "/"))
        self.pushButton_7.setText(_translate("MainWindow", "/"))
        self.pushButton_8.setText(_translate("MainWindow", "/"))
        self.pushButton_9.setText(_translate("MainWindow", "/"))
        self.pushButton_10.setText(_translate("MainWindow", "/"))
        self.pushButton_11.setText(_translate("MainWindow", "/"))
        self.pushButton_12.setText(_translate("MainWindow", "/"))
        self.pushButton_13.setText(_translate("MainWindow", "/"))
        self.pushButton_14.setText(_translate("MainWindow", "/"))
        self.pushButton_15.setText(_translate("MainWindow", "/"))
        self.pushButton_16.setText(_translate("MainWindow", "/"))
        self.pushButton_17.setText(_translate("MainWindow", "/"))
        self.pushButton_18.setText(_translate("MainWindow", "pause"))
        self.pushButton_19.setText(_translate("MainWindow", "contiue"))
        self.label.setText(_translate("MainWindow", ""))
def main():
    app=QApplication(sys.argv)

    test=QMainWindow()
    diaglog=Ui_MainWindow()
    diaglog.setupUi(test)

    test.show()
    sys.exit(app.exec_())
main()